# Lists — Working with Collections of Data

This notebook develops a practical understanding of Python lists and their use in organizing, accessing, modifying, processing, and sorting collections of data.

The concepts build directly on variables, conditionals, loops, strings, and debugging patterns introduced in previous notebooks. Scientific, laboratory, and biological examples are used throughout to ground every concept in real data-handling contexts.

The notebook also explores how lists can be combined with `split()`, `zip()`, loops, conditionals, type conversion, custom sorting (`key=` functions, `lambda`), and list comprehension to process simple structured data without external packages.

---

## Learning Objectives

By completing this notebook, I should be able to:

- Explain what a Python list is and how it differs from a string
- Create lists using square brackets containing homogeneous and heterogeneous data types
- Access list elements using zero-based indexing and negative indexing
- Extract sub-lists using slicing (`[start:stop:step]`)
- Convert structured text and multi-line strings into lists using `.split()` and `.splitlines()`
- Modify existing lists via element replacement, `.append()`, `.extend()`, and `.remove()`
- Explain **list mutability** and contrast it with string immutability
- Combine lists with `for` loops, counters, accumulators, and conditional logic
- Process simple tabular / structured data stored as parallel or nested lists
- Use `zip()` to pair related collections together into unified records
- Sort lists using `.sort()` and `sorted()`, explaining how data types affect sort order
- Use custom sorting keys (`key=`) with functions and `lambda` expressions to sort complex or paired data
- Convert raw string representations of numbers into proper numeric types (`int`, `float`) for sorting and computation
- Combine lists, loops, conditionals, and functions to build structured data-processing workflows

---

### Ground Rule

The goal is not to memorize list methods.

For important operations, I will:

1. **Predict** what will happen before running code
2. **Run** the code cell
3. **Inspect** the resulting state
4. **Change** the example parameters
5. **Explain** what I observed in my own words

I will also **avoid using external packages (such as NumPy or Pandas)** in this notebook so that I master pure Python data structures and operations first.

## 1. What Is a List?

A **list** is an ordered, mutable collection of values enclosed in square brackets `[...]` and separated by commas.

Lists allow us to store, organize, and process multiple related items under a single variable name, eliminating the need to declare repetitive scalar variables.

### Problem: Managing Separate Variables

When tracking multiple biological samples, creating isolated variables becomes unmanageable:

```python
sample_1 = "S001"
sample_2 = "S002"
sample_3 = "S003"

### Solution: Storing Sequences in a List
By grouping related data into a single list, we can pass, inspect, and iterate over the entire dataset efficiently:

```python
sample_ids = ["S001", "S002", "S003"]

print("Contents:", sample_ids)
print("Data type:", type(sample_ids))
print("Number of elements:", len(sample_ids))

### Key Attributes of Python Lists

1. **Ordered:** Elements maintain the exact order in which they are inserted.
2. **Heterogeneous:** A single list can hold mixed data types (`str`, `int`, `float`, `bool`).
3. **Dynamic:** Items can be added, modified, or removed at runtime.

### Practice: List Construction & Inspection

Create three separate lists representing laboratory data, then inspect their data types and lengths:

1. `samples` — A list of 5 sample ID strings (e.g., `"S001"`, `"S002"`, ...)
2. `organisms` — A list of 5 organism name strings (e.g., `"Escherichia coli"`, ...)
3. `concentrations` — A list of 5 numeric concentration measurements in µM (e.g., `12.5`, `8.4`, ...)

In [1]:
# 1. Create lists
samples = ["S001", "S002", "S003", "S004", "S005"]
organisms = [
    "Escherichia coli",
    "Staphylococcus aureus",
    "Pseudomonas aeruginosa",
    "Bacillus subtilis",
    "Saccharomyces cerevisiae",
]
concentrations = [12.5, 8.4, 15.2, 9.1, 11.8]

# 2. Inspect type and length for each list
print("Samples:", samples, "| Type:", type(samples), "| Length:", len(samples))
print(
    "Organisms:", organisms, "| Type:", type(organisms), "| Length:", len(organisms)
)
print(
    "Concentrations:",
    concentrations,
    "| Type:",
    type(concentrations),
    "| Length:",
    len(concentrations),
)

Samples: ['S001', 'S002', 'S003', 'S004', 'S005'] | Type: <class 'list'> | Length: 5
Organisms: ['Escherichia coli', 'Staphylococcus aureus', 'Pseudomonas aeruginosa', 'Bacillus subtilis', 'Saccharomyces cerevisiae'] | Type: <class 'list'> | Length: 5
Concentrations: [12.5, 8.4, 15.2, 9.1, 11.8] | Type: <class 'list'> | Length: 5


### Inspection Question

> **Question:** What specific information does `len()` convey when passed a list? How does this differ from calling `len()` on a string?


#### My Analysis

1. **What `len(list)` measures:** It measures the length of a list (ie how many items are there in the list)
2. **Difference between `len(["S001", "S002"])` vs. `len("S001")`:** `len(["S001", "S002"])` measures how many items are there in the list `["S001", "S002"]`, where as `len("S001")` measures how many characters are there in the string `"S001"`

## 2. Lists vs. Strings

Both strings and lists are **ordered sequences** in Python. 

Because both data structures maintain sequential order, they share a common interface for accessing individual elements (indexing) and sub-sequences (slicing). However, they represent fundamentally different data types.

### Sequence Comparison Setup

Let's compare a DNA sequence represented as a single string versus a list of individual single-character strings:

In [2]:
sequence = "ATGCGTA"
nucleotides = ["A", "T", "G", "C", "G", "T", "A"]

### Indexing Comparison

Accessing element at index `0`:

In [3]:
print("String index [0]:", sequence[0])
print("List index [0]:  ", nucleotides[0])

String index [0]: A
List index [0]:   A


### Slicing Comparison

Extracting the slice `[1:4]` (indices 1, 2, and 3):

In [4]:
print("String slice [1:4]:", sequence[1:4])
print("List slice [1:4]:  ", nucleotides[1:4])

String slice [1:4]: TGC
List slice [1:4]:   ['T', 'G', 'C']


### Type Inspection

Inspecting the data types of the full sequence and the sliced subsets:

In [5]:
print("sequence type:        ", type(sequence))
print("sequence[1:4] type:   ", type(sequence[1:4]))
print("----------------------------------------")
print("nucleotides type:     ", type(nucleotides))
print("nucleotides[1:4] type:", type(nucleotides[1:4]))

sequence type:         <class 'str'>
sequence[1:4] type:    <class 'str'>
----------------------------------------
nucleotides type:      <class 'list'>
nucleotides[1:4] type: <class 'list'>


### Conceptual Investigation

> **Think About It:**
> 1. What core features do strings and lists have in common?
> 2. What is different about the data type returned by slicing a string versus slicing a list?
> 3. Why might representing a biological sequence as a list of elements be useful compared to a single contiguous string?

#### My Analysis

1. **Common features:** Both strings and lists are ordered, zero-indexed collections that support positive indexing (seq[0]), negative indexing (seq[-1]), slicing (seq[1:4]), iteration (for item in seq:), and membership testing (in). Both work natively with len() to measure container length.
2. **Difference in slice output:** Slicing a string returns a substring (a new str object): "ATGC"[0:2] -> "AT". Slicing a list returns a sub-list (a new list object): ["A", "T", "G", "C"][0:2] -> ["A", "T"].
3. **Hypothesis on storing DNA as a list:** Representing a biological sequence as a list of elements (["A", "T", "G", "C"]) instead of a single string ("ATGC") offers key functional advantages in computational biology:
    - Mutability & Site Modification: Strings are immutable, so altering a single nucleotide (e.g., simulating a point mutation or SNP) requires creating an entirely new string in memory. Lists are mutable, allowing direct in-place modification of individual bases or codons (seq[4] = "G")
    - Handling Complex Biological Tokens: A DNA sequence is an array of single characters, but genomic data often involves multi-character tokens like codons (["ATG", "CGA", "TCC"]), restriction fragments, or annotated features. Lists store multi-character tokens cleanly as distinct elements without needing complex index math.
    - Attaching Metadata: Elements in a list can hold richer object structures (such as tuples containing (base, quality_score) per position) rather than raw text characters alone.

## 3. Creating Lists

Lists are created using square brackets `[]`, with elements separated by commas. 

An **empty list** contains no elements (`len() == 0`) and is frequently used as a starting container to accumulate results inside loops.

### Syntax Examples

```python
# Empty list (used for accumulating state)
samples = []

# String list
sample_ids = ["S001", "S002", "S003"]

# Numeric list (floats)
concentrations = [12.5, 8.7, 15.2]

# Boolean list (quality control results)
positive_results = [True, False, True, True]

### Practice: Declaring Initial Data Collections
Write Python code to initialize four distinct lists matching the specified requirements:

1. `sample_ids`: A list of 6 sample ID strings (e.g., `"S001"` through `"S006"`).

2. `concentrations`: A list of 6 numeric concentrations in `µM`.

3. `qc_pass`: A list of 6 Boolean values (`True` / `False`) indicating QC status.

4. `processed_samples`: An empty list designated for downstream pipeline output.

In [5]:
# 1. Six sample IDs
sample_ids = ["S001", "S002", "S003", "S004", "S005", "S006"]

# 2. Six concentrations
concentrations = [1.2, 12.5, 8.7, 15.2, 9.8, 5.1]

# 3. Six QC pass results
qc_pass = [False, True, True, True, True, False]

# 4. Empty list for pipeline accumulation
processed_samples = []

# Inspection
print("sample_ids:", sample_ids, "| Count:", len(sample_ids))
print("concentrations:", concentrations, "| Count:", len(concentrations))
print("qc_pass:", qc_pass, "| Count:", len(qc_pass))
print("processed_samples:", processed_samples, "| Count:", len(processed_samples))

sample_ids: ['S001', 'S002', 'S003', 'S004', 'S005', 'S006'] | Count: 6
concentrations: [1.2, 12.5, 8.7, 15.2, 9.8, 5.1] | Count: 6
qc_pass: [False, True, True, True, True, False] | Count: 6
processed_samples: [] | Count: 0


### Verification Check

> **Question:** Ensure that `sample_ids`, `concentrations`, and `qc_pass` all have an identical length of `6`. Why is keeping parallel lists aligned by index critical when processing experimental metadata?

#### My Analysis

1. **Importance of index alignment across parallel lists:**
Keeping parallel lists aligned by index is critical because Python treats each list as an independent object with no built-in connection to the others.The implicit relationship between Sample ID, Concentration, and QC Status relies entirely on shared index positions:
    - `sample_ids[0] ("S001")` $\rightarrow$ `concentrations[0] (1.2)` $\rightarrow$ `qc_pass[0] (False)`
    - `sample_ids[1] ("S002")` $\rightarrow$ `concentrations[1] (12.5)` $\rightarrow$ `qc_pass[1] (True)`

2. **What Happens When Alignment Breaks?**
If one list becomes mismatched due to an unaligned `.append()`, `.pop()`, or `.remove()` operation:
    - Data Corruption: Experimental metadata gets permanently assigned to the wrong biological samples (e.g., Sample `"S002"` inherits the low concentration and failed QC status of `"S001"`).
    - Silent Scientific Errors: The code will still run without throwing a Python runtime exception (`IndexError`), but it will generate invalid scientific conclusions.
    - Index Errors: If list lengths differ (`len(sample_ids) != len(concentrations)`), iterating with positional index loops (`for i in range(len(sample_ids)):`) risks crashing mid-execution with an `IndexError`

## 4. Lists with Different Data Types

Unlike strict arrays in some lower-level programming languages, a Python list is **heterogeneous**. This means a single list can store elements of various data types (`str`, `int`, `float`, `bool`, or even other lists) within the exact same sequence.

This flexibility allows a single list to act as a structured record holding multiple attributes of a single experimental sample.

### Heterogeneous List Example

In [6]:
sample = ["S001", "E_coli", 12.5, True]

print("Index 0:", sample[0], "| Type:", type(sample[0]))
print("Index 1:", sample[1], "| Type:", type(sample[1]))
print("Index 2:", sample[2], "| Type:", type(sample[2]))
print("Index 3:", sample[3], "| Type:", type(sample[3]))

Index 0: S001 | Type: <class 'str'>
Index 1: E_coli | Type: <class 'str'>
Index 2: 12.5 | Type: <class 'float'>
Index 3: True | Type: <class 'bool'>


### Investigation & Loop Integration

Create a mixed-type list representing a single lab record:
1. Sample ID (e.g., `"S105"`)
2. Organism name (e.g., `"Plasmodium falciparum"`)
3. Concentration measurement (e.g., `45.8`)
4. Quality-control result (e.g., `True`)

Then, use a `for` loop to iterate through the list and print each element along with its specific data type.

In [9]:
# 1. Create heterogeneous sample record
sample_record = ["S105", "Plasmodium falciparum", 45.8, True]

# 2. Iterate through elements and print value + type using a loop
for item in sample_record:
    print(f"Value: {item:<22} | Type: {type(item)}")

Value: S105                   | Type: <class 'str'>
Value: Plasmodium falciparum  | Type: <class 'str'>
Value: 45.8                   | Type: <class 'float'>
Value: 1                      | Type: <class 'bool'>


### Reflection & Analysis

> **Question:** What does this capability tell you about the flexibility of Python lists? What potential risks might arise when performing numerical operations on a list with mixed data types?

#### My Analysis

1. **Flexibility of heterogeneous lists:**
Python lists are generic object containers rather than rigid memory arrays. Because lists store reference pointers to objects rather than contiguous blocks of raw bytes, a single list can seamlessly hold strings, floating-point measurements, Booleans, integers, or even nested sub-lists. This allows you to construct flexible data structures such as representing a complete biological sample record (`["S105", "Plasmodium falciparum", 45.8, True]`) without needing complex custom data classes or strict typing upfront.

2. **Potential risks when processing mixed data in loops:**
While heterogeneous lists offer maximum flexibility, they introduce significant operational risks during numerical processing and data analysis:

    - **`TypeError` Runtime Crashes:** Attempting mathematical or arithmetic operations across a loop assuming all elements are numeric will cause execution to crash.
    - **Silent Logic Errors from String Concatenation:** Python overloads operators like `+` and `*`. If a list contains mixed string and numeric types, calling `a + b` might perform string concatenation instead of addition, producing invalid calculations without raising an error.
    - **Unexpected Sorting Failures:** In Python 3, calling `.sort()` or `sorted()` on a list with mixed unorderable types (e.g., comparing `str` to `float`) triggers an unrecoverable `TypeError: '<' not supported between instances of 'float' and 'str'`.
    - **Defensive Code Overhead:** To process mixed lists safely, you must write additional type-checking guard clauses (`if isinstance(x, (int, float)):`), adding complexity to your pipeline.

## 5. Indexing Lists

Lists use **zero-based indexing**, identical to strings. The first element is located at index `0`, and the last element can be accessed using positive index `len(list) - 1` or negative index `-1`.

### Basic Indexing Syntax

In [1]:
samples = ["S001", "S002", "S003", "S004", "S005"]

print("First element (index 0): ", samples[0])
print("Second element (index 1):", samples[1])
print("Last element (index -1): ", samples[-1])
print("Second to last (index -2):", samples[-2])

First element (index 0):  S001
Second element (index 1): S002
Last element (index -1):  S005
Second to last (index -2): S004


### Prediction Exercise

Given the list:
`samples = ["S001", "S002", "S003", "S004", "S005"]`

Predict the value returned by each expression **before executing the code cell below**:

| Expression | Predicted Value | Actual Value | Match? |
|---|---|---|---|
| `samples[0]` | `___` | | |
| `samples[2]` | `___` | | |
| `samples[-1]` | `___` | | |
| `samples[-3]` | `___` | | |

In [ ]:
samples = ["S001", "S002", "S003", "S004", "S005"]

print("samples[0]  ->", samples[0])
print("samples[2]  ->", samples[2])
print("samples[-1] ->", samples[-1])
print("samples[-3] ->", samples[-3])

### Boundary Experiment & Error Observation

Execute the cell below to test what happens when attempting to access an index beyond the list bounds:

In [2]:
# Boundary test: Attempting to access index 5 on a 5-element list
try:
    print(samples[5])
except IndexError as e:
    print("Caught Exception:", type(e).__name__, "-", e)

Caught Exception: IndexError - list index out of range


### Observation & Debugging Note

> **Observation:** Python raises an `IndexError: list index out of range` when accessing an index that does not exist.
>
> **Key Rule:** For a list containing $N$ elements (`len(samples) == 5`), the valid positive indices are $0$ through $N-1$ (`0` to `4`). Index `5` refers to the $6^{\text{th}}$ element, which does not exist.

## 6. Slicing Lists

Slicing extracts a contiguous sub-list from an existing list without modifying the original container.

The standard syntax is:
`list[start:stop:step]`

- `start`: The index where the slice begins (inclusive). Defaults to `0` if omitted.
- `stop`: The index where the slice ends (**exclusive**). Defaults to `len(list)` if omitted.
- `step`: The stride or interval between elements. Defaults to `1` if omitted.

### Basic Slicing Mechanics

In [3]:
samples = ["S001", "S002", "S003", "S004", "S005", "S006"]

print("samples[:3]   (First 3 elements): ", samples[:3])
print("samples[2:]   (Index 2 to end):   ", samples[2:])
print("samples[1:4]  (Indices 1, 2, 3):  ", samples[1:4])
print("samples[::-1] (Reversed list):    ", samples[::-1])

samples[:3]   (First 3 elements):  ['S001', 'S002', 'S003']
samples[2:]   (Index 2 to end):    ['S003', 'S004', 'S005', 'S006']
samples[1:4]  (Indices 1, 2, 3):   ['S002', 'S003', 'S004']
samples[::-1] (Reversed list):     ['S006', 'S005', 'S004', 'S003', 'S002', 'S001']


### Practice: Numerical Data Extraction

Given the concentration measurements:
`measurements = [12.1, 14.5, 9.8, 17.2, 11.6, 13.4]`

Write slicing expressions to extract each specified subset:

1. The **first three** measurements
2. The **last three** measurements
3. The **second through fourth** measurements (indices 1, 2, and 3)
4. **Every second** measurement (stepping by 2)
5. The measurements in **reverse order**

In [4]:
measurements = [12.1, 14.5, 9.8, 17.2, 11.6, 13.4]

# 1. First three
first_three = measurements[:3]

# 2. Last three
last_three = measurements[-3:]

# 3. Second through fourth
second_to_fourth = measurements[1:4]

# 4. Every second measurement
every_second = measurements[::2]

# 5. Reverse order
reversed_measurements = measurements[::-1]

# Display outputs
print("First three:        ", first_three)
print("Last three:         ", last_three)
print("Second to fourth:   ", second_to_fourth)
print("Every second:       ", every_second)
print("Reversed order:     ", reversed_measurements)

First three:         [12.1, 14.5, 9.8]
Last three:          [17.2, 11.6, 13.4]
Second to fourth:    [14.5, 9.8, 17.2]
Every second:        [12.1, 9.8, 11.6]
Reversed order:      [13.4, 11.6, 17.2, 9.8, 14.5, 12.1]


### Slice Inspection & Verification

> **Question:** Does slicing a list create a brand new list in memory, or does it alter the original `measurements` list? Test this by inspecting `measurements` after running your slices above.

In [5]:
# Code verification test
measurements = [12.5, 8.4, 15.2, 9.1, 11.8, 6.3]

# Extract a slice into a new variable
sub_slice = measurements[1:4]

# Modify the extracted slice
sub_slice[0] = 999.9

# Inspect both objects
print("Extracted Slice:", sub_slice)
print("Original Measurements:", measurements)

Extracted Slice: [999.9, 15.2, 9.1]
Original Measurements: [12.5, 8.4, 15.2, 9.1, 11.8, 6.3]


#### My Observation

1. **Original `measurements` state after slicing:** The original `measurements` list remains completely unchanged after creating and extracting slices. All elements, their positions, and the overall list length stay exactly as they were before the slice operations were executed.
2. **Conclusion:** Slicing a list (`measurements[start:stop]`) creates a brand new list object in memory containing copies of the selected reference pointers. Slicing is a non-destructive read operation—it does not mutate or alter the original source list in any way.

## 7. Splitting Strings into Lists

Real-world scientific data (such as CSV files, FASTA headers, or assay exports) almost always arrives as raw text. 

The `.split()` method divides a string along a specified delimiter and returns the components as a **list of strings**.

### Default Whitespace Splitting
When called without arguments, `.split()` automatically splits on any whitespace (spaces, tabs, newlines):

In [6]:
data = "S001 S002 S003 S004"
samples = data.split()

print("Resulting list:", samples)
print("Data type:     ", type(samples))

Resulting list: ['S001', 'S002', 'S003', 'S004']
Data type:      <class 'list'>


### Splitting on Specific Delimiters (Commas & Biological Sequences)
Passing a character (like `","` or `" "`) splits the text strictly at that delimiter:

In [7]:
# Comma-separated sample string
csv_data = "S001,S002,S003,S004"
csv_samples = csv_data.split(",")
print("Comma-split samples:", csv_samples)

# Space-separated DNA codons
sequence = "ATG CGT TAC GGA"
codons = sequence.split()
print("Extracted codons:  ", codons)

Comma-split samples: ['S001', 'S002', 'S003', 'S004']
Extracted codons:   ['ATG', 'CGT', 'TAC', 'GGA']


### Multi-Line Data Parsing: The Structural Bridge

Consider multi-line raw tabular data representing experimental records:

In [8]:
data = """S001,E_coli,12.5
S002,E_coli,8.7
S003,S_aureus,15.2
S004,S_aureus,11.4"""

# Step 1: Split into rows along newline characters
rows = data.split("\n")

print("All rows as a list:")
print(rows)
print("-" * 40)
print("Row 0:", rows[0])
print("Row 1:", rows[1])

All rows as a list:
['S001,E_coli,12.5', 'S002,E_coli,8.7', 'S003,S_aureus,15.2', 'S004,S_aureus,11.4']
----------------------------------------
Row 0: S001,E_coli,12.5
Row 1: S002,E_coli,8.7


### Two-Dimensional Data Extraction

Once multi-line text is split into a list of row strings, splitting an individual row by `","` produces a list of specific column values:

In [9]:
# Step 2: Split the first row string into individual column fields
first_row_columns = rows[0].split(",")

print("Columns extracted from Row 0:", first_row_columns)
print("Sample ID (Col 0): ", first_row_columns[0])
print("Organism  (Col 1): ", first_row_columns[1])
print("Conc µM   (Col 2): ", first_row_columns[2])

Columns extracted from Row 0: ['S001', 'E_coli', '12.5']
Sample ID (Col 0):  S001
Organism  (Col 1):  E_coli
Conc µM   (Col 2):  12.5


### The Data Parsing Pipeline Architecture

This two-stage transformation forms the fundamental backbone for parsing structured text in Python without external tools:

$$\text{Raw Multi-line String} \xrightarrow{\quad \text{.split("\textbackslash n")} \quad} \text{List of Row Strings} \xrightarrow{\quad \text{.split(",")} \quad} \text{List of Column Elements}$$

> **Key Takeaway:** Master this two-step pattern. It is the exact bridge required for reading file streams, parsing CSVs, and executing custom sorting logic on multi-attribute scientific records.

### Reflection & Practice

> **Question:** In `first_row_columns[2]`, what is the data type of `"12.5"`? What must happen before performing mathematical calculations or numeric sorting on this value?

### My Analysis

1. **Current data type of `first_row_columns[2]`:** Its data type is `str` (string): `"12.5"`. The `.split()` method always produces a list containing string elements, regardless of whether those characters represent text or numbers.

2. **Required conversion step before math or sorting:** It must be explicitly converted to a numeric floating-point type using `float(first_row_columns[2])` (or `int()` for whole integers).

## 8. Modifying Lists

Unlike strings—which are **immutable** and cannot be changed in place—lists are **mutable**. Individual elements can be modified, added, or removed after the list container has been created.

---

### 8.1 Replacing Elements (Item Assignment)

You can update a value directly using its zero-based index:

In [10]:
samples = ["S001", "S002", "S003"]
print("Original list:", samples)

# Replace element at index 1
samples[1] = "S100"
print("Modified list:", samples)

Original list: ['S001', 'S002', 'S003']
Modified list: ['S001', 'S100', 'S003']


#### Practice: Element Replacement

Change the third sample ID (`"S003"`) to `"S999"` without re-declaring the list:

In [13]:
samples = ["S001", "S100", "S003"]

# Replace the third element in place:
samples[2] = "S999"


print("Updated samples:", samples)

Updated samples: ['S001', 'S100', 'S999']


### 8.2 Adding Elements with `.append()`

The `.append()` method adds a single element to the end of an existing list:

In [14]:
samples = ["S001", "S002", "S003"]
samples.append("S004")

print("List after append:", samples)

List after append: ['S001', 'S002', 'S003', 'S004']


#### Critical Traps `.append()` In-Place Mutation & `None`

Observe what happens when you assign the result of `.append()` to a variable:

In [15]:
samples = ["S001", "S002", "S003", "S004"]

# Critical Trap: Attempting to store return value of append()
result = samples.append("S005")

print("Variable 'result': ", result)
print("Updated 'samples':", samples)

Variable 'result':  None
Updated 'samples': ['S001', 'S002', 'S003', 'S004', 'S005']


> **Important Observation:** `.append()` mutates the existing list **in place**. It returns `None`.
>
> Writing `samples = samples.append("S005")` destroys your list by re-assigning the variable name to `None`. Always call `samples.append(...)` as an isolated statement.

### 8.3 Removing Elements with `.remove()`

The `.remove()` method searches for the **first matching value** in the list and deletes it:

In [16]:
samples = ["S001", "S002", "S003", "S004"]

samples.remove("S002")

print("List after removing 'S002':", samples)

List after removing 'S002': ['S001', 'S003', 'S004']


#### Investigation: Removing Non-Existent Elements

Execute the cell below to test what happens when `.remove()` is given a value not present in the list:

In [17]:
samples = ["S001", "S003", "S004"]

# Attempting to remove an missing element:
try:
    samples.remove("S999")
except ValueError as e:
    print("Caught Exception:", type(e).__name__, "-", e)

Caught Exception: ValueError - list.remove(x): x not in list


### Observation & Debugging Note

> **Observation:** Python raises a `ValueError: list.remove(x): x not in list` when trying to remove an item that does not exist.
>
> **Prevention Pattern:** Check membership using `in` *before* attempting removal:
> ```python
> if "S999" in samples:
>     samples.remove("S999")
> ```

#### My Reflection

> **Question:** Why is understanding in-place mutation crucial when passing biological datasets (like large sequences or assay tables) into functions in Python?

1. **Answer:** Understanding in-place mutation is critical because Python passes objects (including lists) by object reference. When you pass a list into a function, any modifying operations performed inside the function—such as `.append()`, `.remove()`, or item assignment (`list[i] = val`) will permanently mutate the original dataset outside the function. 
If you do not intend to alter the raw biological input data (such as an original sequence or assay table), altering it in-place can corrupt your downstream analyses or lead to silent bugs. To avoid unintended side effects, you must explicitly create a copy of the list (e.g., `data_copy = raw_data.copy()` or `data_copy = raw_data[:]`) before modifying it inside functions.

## 9. Mutability & Variable References

A **mutable** object is one whose internal state can be altered in place after creation without changing its memory identity. 

Lists are mutable; strings and integers are immutable. While mutability allows for efficient in-place updates, it introduces a subtle behavior when binding multiple variable names to the same list container.


### In-Place Element Mutation

Direct item assignment modifies the underlying list object directly:

In [18]:
samples = ["S001", "S002", "S003"]
print("Initial samples:", samples)

samples[0] = "S100"
print("Mutated samples:", samples)

Initial samples: ['S001', 'S002', 'S003']
Mutated samples: ['S100', 'S002', 'S003']


### The Shared Reference Experiment (Aliasing)

Observe what happens when we assign an existing list variable to a new variable name:

In [19]:
original = ["A", "B", "C"]

# Create an alias pointing to 'original'
alias = original

# Mutate the list through 'alias'
alias[0] = "X"

print("original:", original)
print("alias:   ", alias)

original: ['X', 'B', 'C']
alias:    ['X', 'B', 'C']


### Conceptual Investigation

> **Think About It:**
> 1. Why did modifying `alias[0]` also change the contents printed by `original`?
> 2. Did `alias = original` create a brand-new copy of the list, or did it assign a second label to the exact same list object?
> 3. How can you verify using Python's built-in `id()` function whether two variables point to the same memory identity?

In [20]:
# Verification using memory address inspection:
print("Memory ID of original:", id(original))
print("Memory ID of alias:   ", id(alias))
print("Are they identical?   ", id(original) == id(alias))

Memory ID of original: 133211112115712
Memory ID of alias:    133211112115712
Are they identical?    True


### Key Takeaway: Variable Names are Labels, Not Boxes

In Python, variables do not "contain" data directly; they act as **pointers or reference labels** attached to objects in memory.

$$\text{original} \longrightarrow \begin{bmatrix} \text{"X"}, & \text{"B"}, & \text{"C"} \end{bmatrix} \longleftarrow \text{alias}$$

- **Aliasing:** Writing `alias = original` creates two references pointing to a **single** list in memory. Any mutation through one label is visible through the other.
- **Copying:** To create an independent duplicate list that can be mutated safely without affecting the original, use explicit slicing (`copy_list = original[:]`) or `.copy()` (`copy_list = original.copy()`).

#### My Analysis

1. **Explanation of alias mutation behavior:** Writing `alias = original` does not create a new list or allocate new memory; it simply binds a second variable label (`alias`) to the exact same list object in memory. Because both variable names point to the same memory identity (`id(original) == id(alias)`), modifying the list through `alias[0] = "X"` mutates the shared underlying object directly, making the change visible when accessing `original`.
2. **How to safely duplicate a list before modifying it:** To create an independent duplicate (a shallow copy) that can be safely mutated without altering the original list, use one of the following explicit copying techniques:

    - List slicing: `copy_list = original[:]`

    - The `.copy()` method: `copy_list = original.copy()`

    - The `list()` constructor: c`opy_list = list(original)`

In [21]:
original = ["A", "B", "C"]

# Create an independent shallow copy
independent_copy = original.copy()

# Mutate the copy
independent_copy[0] = "X"

print("original:        ", original)  # Remains ['A', 'B', 'C']
print("independent_copy:", independent_copy)  # Becomes ['X', 'B', 'C']
print("Do they share memory ID?", id(original) == id(independent_copy))  # False

original:         ['A', 'B', 'C']
independent_copy: ['X', 'B', 'C']
Do they share memory ID? False


## 10. Lists + Conditionals + Loops

Lists become exponentially more powerful when combined with loops and conditional logic. 

This combination enables us to automate decision-making across entire datasets—evaluating quality control metrics, categorizing measurements, and filtering outliers in a single execution pass.


### Batch Classification Example

Iterating over a collection of experimental concentration measurements ($\mu\text{M}$) and applying threshold logic:

In [22]:
concentrations = [8.2, 12.5, 15.1, 6.7, 18.3]

for concentration in concentrations:
    if concentration < 10:
        print(f"Low:    {concentration:>5.1f} µM")
    elif concentration <= 15:
        print(f"Normal: {concentration:>5.1f} µM")
    else:
        print(f"High:   {concentration:>5.1f} µM")

Low:      8.2 µM
Normal:  12.5 µM
High:    15.1 µM
Low:      6.7 µM
High:    18.3 µM


### Independent Practice: Scientific Threshold Classification

1. Define a list of **at least 6** concentration measurements.
2. Select scientifically justified thresholds for **Low**, **Normal**, and **High** ranges.
3. Write a `for` loop using `if`/`elif`/`else` structures to classify and format each item.
4. Document the scientific rationale behind your chosen threshold boundaries in the reflection block below.

In [29]:
# 1. Define dataset
concentrations = [3.4, 11.2, 24.8, 8.9, 15.0, 31.5]

# 2. Define operational thresholds
LOW_THRESHOLD = 10.0  # Below minimum effective concentration (MEC)
HIGH_THRESHOLD = 25.0  # Above maximum safe concentration / toxicity limit

# 3. Write classification loop:
for conc in concentrations:
    if conc < LOW_THRESHOLD:
        print(f"Low (Sub-therapeutic):  {conc:>5.1f} µM")
    elif conc <= HIGH_THRESHOLD:
        print(f"Normal (Therapeutic):   {conc:>5.1f} µM")
    else:
        print(f"High (Toxic Range):     {conc:>5.1f} µM")

Low (Sub-therapeutic):    3.4 µM
Normal (Therapeutic):    11.2 µM
Normal (Therapeutic):    24.8 µM
Low (Sub-therapeutic):    8.9 µM
Normal (Therapeutic):    15.0 µM
High (Toxic Range):      31.5 µM


### Rationale & Scientific Reflection

> **Scientific Justification:** Explain why you selected your specific cutoff values. How do defined boundary thresholds affect sample processing decisions in an automated bioassay pipeline?

#### My Analysis

1. **Selected thresholds:**
    - ow: $< 10.0\ \mu\text{M}$
    - Normal: $10.0\ \mu\text{M} - 25.0\ \mu\text{M}$
    - High: $> 25.0\ \mu\text{M}$
2. **Scientific rationale for cutoffs:**
In pharmacodynamics and drug discovery assays, the $10.0\ \mu\text{M}$ lower bound represents the **Minimum Effective Concentration (MEC)** required to elicit a significant biological response (e.g., target enzyme inhibition). Concentrations below $10.0\ \mu\text{M}$ are sub-therapeutic and biologically ineffective. The $25.0\ \mu\text{M}$ upper bound corresponds to the **Maximum Tolerated Concentration (MTC)** before off-target cellular toxicity or compound precipitation occurs in assay media
3. **Impact on pipeline logic:**
Establishing discrete, hard boundary thresholds allows an automated high-throughput screening (HTS) pipeline to triage compound plates without human intervention:
    - **Sub-therapeutic samples ($< 10.0\ \mu\text{M}$):** Automatically flagged for re-concentration or hit-validation re-testing.
    - **Therapeutic range ($10.0 - 25.0\ \mu\text{M}$):** Passed downstream for secondary IC50 dose-response profiling.
    - **Toxic range ($> 25.0\ \mu\text{M}$):** Flagged as toxic hits, automatically triggering serial dilution requests in the liquid handler to re-assess at safer physiological doses.

## 11. Processing Structured Data

Experimental datasets are almost always formatted in tabular rows and columns (such as CSV exports or assay output streams). 

Before relying on high-level libraries, learning to manually dissect raw text into structured lists builds essential problem-solving skills for handling file streams, handling parsing errors, and performing manual data cleaning.

---

### 11.1 Splitting Raw Text into Rows

We begin with a multi-line string where each line represents a single sample record:

In [2]:
data = """S001,E_coli,12.5
S002,E_coli,8.7
S003,S_aureus,15.2
S004,S_aureus,11.4"""

# Step 1: Split multi-line text into a list of row strings
rows = data.split("\n")

print("Raw rows list:", rows)
print("-" * 40)

# Iterate through row strings
for row in rows:
    print("Row string:", row)

Raw rows list: ['S001,E_coli,12.5', 'S002,E_coli,8.7', 'S003,S_aureus,15.2', 'S004,S_aureus,11.4']
----------------------------------------
Row string: S001,E_coli,12.5
Row string: S002,E_coli,8.7
Row string: S003,S_aureus,15.2
Row string: S004,S_aureus,11.4


### 11.2 Rows and Columns Extraction

Next, inside our loop, we split each individual row string by its comma delimiter `(",")` to extract specific attributes and convert string representations of numbers into actual numerical data types (`float`):

In [4]:
for row in rows:
    # Step 2: Split row string into column elements
    columns = row.split(",")
    
    # Step 3: Unpack fields and cast data types
    sample_id = columns[0]
    organism = columns[1]
    concentration = float(columns[2])
    
    print(sample_id, organism, concentration)

S001 E_coli 12.5
S002 E_coli 8.7
S003 S_aureus 15.2
S004 S_aureus 11.4


### Independent Practice: Formatted Text Generation
Modify the loop above so that each row is displayed in this exact formatted layout:

`Sample S001 | Organism: E_coli | Concentration: 12.5`

In [6]:
for row in rows:
    columns = row.split(",")
    
    sample_id = columns[0]
    organism = columns[1]
    concentration = float(columns[2])
    
    # Formatted print statement
    print(f"Sample {sample_id} | Organism: {organism} | Concentration: {concentration}")

Sample S001 | Organism: E_coli | Concentration: 12.5
Sample S002 | Organism: E_coli | Concentration: 8.7
Sample S003 | Organism: S_aureus | Concentration: 15.2
Sample S004 | Organism: S_aureus | Concentration: 11.4


## 12. zip()
The built-in `zip()` function aggregates corresponding elements from two or more parallel sequences, pairing items by index into tuples.

In [7]:
sample_ids = ["S001", "S002", "S003"]
organisms = ["E_coli", "E_coli", "S_aureus"]

# Combine lists into zipped pairs
pairs = zip(sample_ids, organisms)
print("Zipped object converted to list:", list(pairs))

Zipped object converted to list: [('S001', 'E_coli'), ('S002', 'E_coli'), ('S003', 'S_aureus')]


### Iterating through multiple sequences simultaneously:

In [8]:
sample_ids = ["S001", "S002", "S003"]
organisms = ["E_coli", "E_coli", "S_aureus"]
concentrations = [12.5, 8.7, 15.2]

for sample_id, organism, concentration in zip(sample_ids, organisms, concentrations):
    print(f"{sample_id:<6} | {organism:<10} | {concentration:>5.1f} µM")

S001   | E_coli     |  12.5 µM
S002   | E_coli     |   8.7 µM
S003   | S_aureus   |  15.2 µM


### Investigation: Mismatched Sequence Lengths
> ***Experiment:*** What happens when lists passed to `zip()` have different lengths? Create two lists of different lengths and test your prediction.

In [10]:
short_list = ["S001", "S002"]
long_list = [12.5, 8.7, 15.2, 22.1]

# 1. Default zip truncation (Silent)
mismatched_zip = list(zip(short_list, long_list))
print("Default zip result:", mismatched_zip)
print("Length of result:   ", len(mismatched_zip))

# 2. Strict zip safeguard (Enforces exact alignment)
try:
    strict_pairs = list(zip(short_list, long_list, strict=True))
except ValueError as e:
    print("\nStrict Zip Exception Caught:", e)

Default zip result: [('S001', 12.5), ('S002', 8.7)]
Length of result:    2

Strict Zip Exception Caught: zip() argument 2 is longer than argument 1


#### My Analysis

1. ***Observed zip() truncation behavior:*** `zip()` stops pairing elements as soon as the shortest input sequence is exhausted. In the experiment, even though `long_list` contains `4` elements, `zip()` terminates after 2 iterations because `short_list` has only `2` elements. The resulting list length is `2`, and the trailing elements in `long_list (15.2, 22.1)` are completely ignored.

2. ***Data loss risks in laboratory pipelines:*** Truncation happens silently without raising an error or warning, which creates major operational risks:

    - ***Silent Data Loss:*** Assays, concentrations, or metadata at the end of longer lists are silently dropped from calculation passes or file exports.

    - ***False Success Rates:*** Unprocessed samples will not show up in output reports, making pipelines appear as if all data was successfully processed when trailing records were omitted.

    - ***Pipeline Safeguard (`strict=True`):*** In `Python 3.10+`, you can pass `zip(list1, list2, strict=True)`. If list lengths do not match, Python immediately raises a `ValueError` instead of silently truncating data, protecting experimental integrity.

## 13. Sorting Lists

Sorting arranges sequence values into a defined order. Python provides two distinct ways to sort:

* `sorted(list)`: Function that returns a new sorted list, leaving the original untouched.
* `list.sort()`: Method that mutates the existing list in-place and returns `None`.

In [12]:
values = [14, 2, 19, 7, 11]

# Out-of-place sorting
sorted_values = sorted(values)
print("Original values after sorted():", values)
print("Returned sorted list:         ", sorted_values)
print("-" * 45)

# In-place sorting
values.sort()
print("Original values after .sort(): ", values)

Original values after sorted(): [14, 2, 19, 7, 11]
Returned sorted list:          [2, 7, 11, 14, 19]
---------------------------------------------
Original values after .sort():  [2, 7, 11, 14, 19]


### Investigation: sorted() vs .sort()

#### Questions for Reflection
1. Does `sorted()` modify the original list?
2. Does `.sort()` modify the original list?
3. What is the return value of `.sort()` vs `sorted()`?

#### My Analysis

1. **Does `sorted()` modify the original list?**  
   **No.** `sorted()` creates and returns a brand-new list object in memory, leaving the original list (`[14, 2, 19, 7, 11]`) untouched.

2. **Does `.sort()` modify the original list?**  
   **Yes.** `.sort()` mutates the existing list directly in memory (*in-place*).

3. **What is the return value of `.sort()` vs `sorted()`?**  
   * `sorted(values)` returns the **new sorted `list`** (`[2, 7, 11, 14, 19]`).
   * `values.sort()` returns **`None`**.

> **Critical Trap:** Never write `values = values.sort()`. Because `.sort()` returns `None`, assigning its output back to the original variable name overwrites and destroys your dataset!

## 14. Sorting and Data Types

Data type directly governs sort behavior. Numbers sort numerically, while text strings sort lexicographically (character by character according to ASCII values).

In [13]:
# Numeric sort
numbers = [2, 10, 3, 25]
numbers.sort()
print("Sorted integers:", numbers)

# String sort
string_numbers = ["2", "10", "3", "25"]
string_numbers.sort()
print("Sorted strings: ", string_numbers)

Sorted integers: [2, 3, 10, 25]
Sorted strings:  ['10', '2', '25', '3']


### Investigation: The Lexicographical Trap

#### Question for Reflection
Why does `"10"` sort before `"3"` when stored as strings?

#### My Analysis

1. **Explanation of string comparison mechanics:**  
   Strings are sorted **lexicographically (character-by-character from left to right)** based on their ASCII/Unicode values, rather than as complete numerical quantities. When Python compares `"10"` and `"3"`, it evaluates the first character of each string: `'1'` vs. `'3'`. Because `'1'` has a lower ASCII code ($49$) than `'3'` ($51$), `"10"` is placed before `"3"`, completely ignoring the numeric value of the full string.

2. **Why casting strings to `int` or `float` before sorting is critical:**  
   Explicitly converting string inputs into numeric types (`int()` or `float()`) shifts Python from character-based ASCII evaluation to true **mathematical evaluation**. Without type casting, multi-digit numeric strings will sort out of order (e.g., `"100"` comes before `"2"`), leading to corrupted rankings, invalid threshold sorting, and broken experimental reports.

## 15. Reconstructing Tabular Parsing & Type Conversion

Now we bring string splitting, list creation, type conversion, and loops together to process structured multi-attribute data.

### Step-by-Step Data Parsing Pipeline

In [14]:
# Raw multi-line CSV representation
class_data = """Ava,Ben,Carl,Dana
85,92,78,100"""

# Step 1: Split raw text into row strings along newline characters
rows = class_data.split("\n")
print("Rows:", rows)

# Step 2: Split row strings into individual column fields
students = rows[0].split(",")
grades = rows[1].split(",")

print("Students (raw strings):", students)
print("Grades (raw strings):  ", grades)

# Step 3: Explicit numeric type conversion using index-based loop
for i in range(len(grades)):
    grades[i] = int(grades[i])

print("Grades (converted ints):", grades)
print("Type of first grade:    ", type(grades[0]).__name__)

Rows: ['Ava,Ben,Carl,Dana', '85,92,78,100']
Students (raw strings): ['Ava', 'Ben', 'Carl', 'Dana']
Grades (raw strings):   ['85', '92', '78', '100']
Grades (converted ints): [85, 92, 78, 100]
Type of first grade:     int


### Investigation: Two-Stage Parsing Mechanics

#### Questions for Reflection
1. Why must `split("\n")` be executed before `split(",")`?
2. What would happen if you attempted to call `.split(",")` directly on the `class_data` variable?

#### My Analysis (Completed)

1. **Importance of split order (`\n` before `,`):**  
   Splitting by `"\n"` first preserves the **two-dimensional tabular structure** of the dataset by separating records into individual row strings. This enables us to isolate specific attributes (e.g., header/metadata row vs. numerical payload row) before extracting individual column elements.

2. **Consequence of splitting on `,` directly:**  
   Calling `class_data.split(",")` directly would collapse rows across newline boundaries, producing `['Ava', 'Ben', 'Carl', 'Dana\n85', '92', '78', '100']`. Notice how `'Dana\n85'` gets merged into a single element containing an embedded newline character, making explicit type conversion (`int()`) on that element fail with a `ValueError`.

## 16. Sorting Paired Data & Tuple Order

When Python sorts a list of tuples, it compares elements index-by-index starting at index 0. If elements at index 0 are identical, it compares index 1.
Therefore, the positional order of values inside zipped tuples dictates the primary sorting key.

In [15]:
# Setup data from Section 15
students = ["Ava", "Ben", "Carl", "Dana"]
grades = [85, 92, 78, 100]

# Experiment 1: Zip with grades as the FIRST element (index 0)
grade_pairs = list(zip(grades, students))
print("Raw grade pairs:    ", grade_pairs)

grade_pairs.sort()
print("Sorted by grade:    ", grade_pairs)
print("-" * 55)

# Experiment 2: Zip with student names as the FIRST element (index 0)
name_pairs = list(zip(students, grades))
print("Raw name pairs:     ", name_pairs)

name_pairs.sort()
print("Sorted by name:     ", name_pairs)

Raw grade pairs:     [(85, 'Ava'), (92, 'Ben'), (78, 'Carl'), (100, 'Dana')]
Sorted by grade:     [(78, 'Carl'), (85, 'Ava'), (92, 'Ben'), (100, 'Dana')]
-------------------------------------------------------
Raw name pairs:      [('Ava', 85), ('Ben', 92), ('Carl', 78), ('Dana', 100)]
Sorted by name:      [('Ava', 85), ('Ben', 92), ('Carl', 78), ('Dana', 100)]


### Key Insight & Reflection: Tuple Comparison Mechanics

#### Questions for Reflection
When sorting zipped pairs without custom functions, how does changing the order of arguments in `zip()` change how Python sorts the list?

#### My Analysis
1. **Effect of `zip(grades, students)` vs `zip(students, grades)`:**  
   Python evaluates tuple comparisons sequentially, starting at **index 0**. 
   * **`zip(grades, students)`** places numeric grades at index `0`, forcing `.sort()` to perform a **numerical sort by score** ($78 \rightarrow 85 \rightarrow 92 \rightarrow 100$).
   * **`zip(students, grades)`** places student name strings at index `0`, forcing `.sort()` to perform an **alphabetical sort by name** ($"Ava" \rightarrow "Ben" \rightarrow "Carl" \rightarrow "Dana"$).

2. **How to sort in descending order (highest score first) using tuple position:**  
   To rank highest scores first without a custom key function, zip with `grades` at index `0` and pass **`reverse=True`** into `.sort()` or `sorted()`:
   ```python
   grade_pairs = list(zip(grades, students))
   grade_pairs.sort(reverse=True)
   # Result: [(100, 'Dana'), (92, 'Ben'), (85, 'Ava'), (78, 'Carl')]

## 17. Custom Sorting with `key=` and `lambda`

In Section 16, we saw that Python sorts tuples based on the element at index `0`. Swapping the order in `zip()` allowed us to change what Python sorts by.

However, rebuilding or re-zipping lists every time we want to sort by a different attribute is inefficient and clunky. 

Instead, Python allows us to keep our data structured as `(student, grade)` or `(sample_id, concentration)` and pass a **custom sorting key** using the `key=` parameter and a `lambda` expression.

---

### 17.1 What Is a `lambda` Expression?

A `lambda` expression is a small, anonymous (unnamed) function defined on a single line:

```text
    Key argument in sort
         │
  key = lambda record: record[1]
                 │        │
  Input parameter        Extracted value used as the sorting criteria
  (each item in list)    (e.g., index 1)

### 17.2 Sorting (`name`, `grade`) Records Without Re-zipping

In [16]:
students = ["Ava", "Ben", "Carl", "Dana"]
grades = [85, 92, 78, 100]

# Standard structure: (Name at index 0, Grade at index 1)
pairs = list(zip(students, grades))
print("Original paired data:           ", pairs)

# Default Sort (Sorts by index 0 — Name)
by_name = sorted(pairs)
print("Sorted by Name (default index 0):", by_name)

# Custom Sort with key=lambda (Sorts by index 1 — Grade)
by_grade = sorted(pairs, key=lambda record: record[1])
print("Sorted by Grade (custom index 1):", by_grade)

Original paired data:            [('Ava', 85), ('Ben', 92), ('Carl', 78), ('Dana', 100)]
Sorted by Name (default index 0): [('Ava', 85), ('Ben', 92), ('Carl', 78), ('Dana', 100)]
Sorted by Grade (custom index 1): [('Carl', 78), ('Ava', 85), ('Ben', 92), ('Dana', 100)]


### 17.3 Sorting in Descending Order

In [17]:
top_grades = sorted(pairs, key=lambda record: record[1], reverse=True)
print("Ranked by Grade (Highest First):", top_grades)

Ranked by Grade (Highest First): [('Dana', 100), ('Ben', 92), ('Ava', 85), ('Carl', 78)]


### Independent Practice: Multi-Attribute Sorting Pipeline

In [19]:
# Raw multi-line assay output stream
assay_raw = """S001,S002,S003,S004
15.2,8.7,100.4,12.0"""

# Step 1: Split string into rows and row elements
rows = assay_raw.strip().split("\n")
sample_ids = rows[0].split(",")
raw_concentrations = rows[1].split(",")

# Step 2: Convert concentration strings to floats using a loop
concentrations = []
for val in raw_concentrations:
    concentrations.append(float(val))

# Step 3: Zip IDs and concentrations into paired tuples: (ID, Concentration)
samples = list(zip(sample_ids, concentrations))

# Step 4: User interaction
print("Select Sort Criteria:")
print("1: Sort by Concentration\n2: Sort by Sample ID")
choice = input("Enter choice (1 or 2): ")

# Step 5: Perform custom in-place sorting using key=lambda
if choice == "1":
    # Sort in-place by concentration (index 1)
    samples.sort(key=lambda record: record[1])
elif choice == "2":
    # Sort in-place by sample ID (index 0)
    samples.sort(key=lambda record: record[0])

# Step 6: Display formatted results
print("\n--- Sorted Assay Report ---")
for sample_id, conc in samples:
    print(f"Sample: {sample_id:<6} | Concentration: {conc:>6.2f} µM")

Select Sort Criteria:
1: Sort by Concentration
2: Sort by Sample ID

--- Sorted Assay Report ---
Sample: S001   | Concentration:  15.20 µM
Sample: S002   | Concentration:   8.70 µM
Sample: S003   | Concentration: 100.40 µM
Sample: S004   | Concentration:  12.00 µM


### Lambda & Custom Sorting Reflection

#### Questions for Reflection
1. What parameter does `record` receive during each evaluation step of `lambda record: record[1]`?
2. Why is `key=lambda x: x[1]` preferred over re-building `zip(concentrations, sample_ids)` every time you need to sort?
3. How would you sort a list of DNA sequence strings `["ATGCG", "AT", "ATGCPGA", "A"]` by sequence length rather than alphabetical order using `key=`?

#### My Analysis

1. **What parameter does `record` receive during each evaluation step of `lambda record: record[1]`?**  
   `record` sequentially receives **a single element (in this case, one tuple)** from the list being sorted (e.g., `('S001', 15.2)`). The expression extracts `record[1]` (`15.2`), which Python uses as the comparison key for ordering that tuple.

2. **Why is `key=lambda x: x[1]` preferred over re-building `zip(concentrations, sample_ids)` every time you need to sort?**  
   Using a `key` function decouples data structure from sorting order. Re-zipping creates new tuple containers and re-allocates memory every time you switch attributes. `key=lambda` allows you to maintain a **single canonical schema** `(sample_id, concentration)` across your entire data pipeline while dynamically sorting by any attribute on demand.

3. **How would you sort a list of DNA sequence strings `["ATGCG", "AT", "ATGCPGA", "A"]` by sequence length rather than alphabetical order using `key=`?**  
   Pass Python's built-in `len` function directly as the key argument:
   ```python
   sequences = ["ATGCG", "AT", "ATGCPGA", "A"]
   sorted_sequences = sorted(sequences, key=len)
   # Result: ['A', 'AT', 'ATGCG', 'ATGCPGA']

## 18. Independent Practice

Apply the core list concepts developed across this notebook—indexing, slicing, mutability, manual accumulators, string parsing, and custom sorting—to solve the following problem set without using external packages like NumPy or Pandas.

---

### Exercise 1: Sample List Mechanics

Given the initial sample string representation:
`"S001\nS002\nS003\nS004"`

**Tasks:**
1. Parse the text string into a list of sample ID strings using `.split()`.
2. Extract and print the **first** and **last** samples using zero-based and negative indexing.
3. Append a fifth sample (`"S005"`) to the list using `.append()`.
4. Replace the second sample (`"S002"`) with `"S100"` in-place via indexing assignment.
5. Remove the third sample (`"S003"`) using `.remove()`.
6. Print the final list state to verify in-place mutability.

In [29]:
# Exercise 1: Sample List Mechanics

raw_samples = """S001
S002
S003
S004"""

# 1. Parse the text string into a list of sample ID strings using `.split()`.
sample_id = raw_samples.split("\n")
print("1. Parsed list:", sample_id)

# 2. Extract and print the first and last samples using zero-based and negative indexing.
print(f"2. First sample: {sample_id[0]} | Last sample: {sample_id[-1]}")

# 3. Append a fifth sample ("S005") to the list using `.append()`.
sample_id.append("S005")
print("3. After append:", sample_id)

# 4. Replace the second sample ("S002") with "S100" in-place via indexing assignment.
sample_id[1] = "S100"
print("4. After index replacement:", sample_id)

# 5. Remove the third sample ("S003") using `.remove()`.
sample_id.remove("S003")
print("5. After removing 'S003':", sample_id)

# 6. Print the final list state to verify in-place mutability.
print("6. Final list state:", sample_id)

1. Parsed list: ['S001', 'S002', 'S003', 'S004']
2. First sample: S001 | Last sample: S004
3. After append: ['S001', 'S002', 'S003', 'S004', 'S005']
4. After index replacement: ['S001', 'S100', 'S003', 'S004', 'S005']
5. After removing 'S003': ['S001', 'S100', 'S004', 'S005']
6. Final list state: ['S001', 'S100', 'S004', 'S005']


### Exercise 2: Concentration Metrics Accumulation
Given the collection of assay yield measurements ($\mu\text{M}$):

`concentrations = [12.5, 8.2, 15.7, 9.1, 21.3, 11.8]`

***Tasks:***
Without using built-in functions like `sum()` or `max()`, write a single `for` loop to manually:
1. Accumulate the total sum of concentrations.
2. Compute the arithmetic mean ($\mu = \frac{\sum x}{N}$).
3. Count how many samples exceed a threshold of $10.0\ \mu\text{M}$.
4. Track and identify the maximum concentration value in the list.

In [36]:
# Exercise 2: Concentration Metrics Accumulation

concentrations = [12.5, 8.2, 15.7, 9.1, 21.3, 11.8]

# Initialize accumulator variables
total_sum = 0.0
above_threshold_count = 0
max_concentration = concentrations[0]  # Initialize with the first element

THRESHOLD = 10.0

# Single loop executing all accumulation tasks manually
for conc in concentrations:
    # 1. Accumulate total sum
    total_sum += conc

    # 3. Count samples exceeding 10.0 uM threshold
    if conc > THRESHOLD:
        above_threshold_count += 1

    # 4. Track maximum value manually without max()
    if conc > max_concentration:
        max_concentration = conc

# 2. Compute arithmetic mean (N = len(concentrations))
arithmetic_mean = total_sum / len(concentrations)

# Display accumulated metrics
print(f"Total Sum:                {total_sum:>6.2f} µM")
print(f"Arithmetic Mean:          {arithmetic_mean:>6.2f} µM")
print(f"Samples > {THRESHOLD} µM:      {above_threshold_count:>6d}")
print(f"Maximum Concentration:    {max_concentration:>6.2f} µM")

Total Sum:                 78.60 µM
Arithmetic Mean:           13.10 µM
Samples > 10.0 µM:           4
Maximum Concentration:     21.30 µM


### Excercise 3: Manual DNA Base Composition Analysis
Given the single DNA sequence string:

`sequence = "ATGCGATCGGCTA"`

***Tasks:***
1. Convert the `sequence` string into a list of individual base characters.
2. Initialize separate counter variables for `A`, `T`, `G`, and `C`.
3. Use a `for` loop with `if`/`elif` conditionals to iterate over the list and increment base counts.
4. Compute and display the overall **GC-content percentage**:
$$\text{GC \%} = \left( \frac{\text{G} + \text{C}}{\text{Total Bases}} \right) \times 100$$

In [44]:
# Exercise 3: Manual DNA Base Composition Analysis

sequence = "ATGCGATCGGCTA"

# 1. Convert sequence string into a list of individual base characters
nucleotides = list(sequence)
print("Parsed nucleotides:", nucleotides)

# 2. Initialize separate counter variables for A, T, G, and C
a_count = 0
t_count = 0
g_count = 0
c_count = 0

# 3. Use a for loop with if/elif conditionals to iterate and increment base counts
for nucleotide in nucleotides:
    if nucleotide == "A":
        a_count += 1
    elif nucleotide == "T":
        t_count += 1
    elif nucleotide == "G":
        g_count += 1
    elif nucleotide == "C":
        c_count += 1

# 4. Compute overall GC-content percentage
total_bases = len(nucleotides)
gc_content = ((g_count + c_count) / total_bases) * 100

# Formatted Sequence Output Report
print(
    f"""
    ========== Sequence Report ==========
    Adenine (A):               {a_count:>6d}
    Thymine (T):               {t_count:>6d}
    Guanine (G):               {g_count:>6d}
    Cytosine (C):              {c_count:>6d}
    -------------------------------------
    Total Sequence Length:     {total_bases:>6d} bases
    GC-Content Percentage:     {gc_content:>6.2f}%
    =====================================
"""
)

Parsed nucleotides: ['A', 'T', 'G', 'C', 'G', 'A', 'T', 'C', 'G', 'G', 'C', 'T', 'A']

    ========== Sequence Report ==========
    Adenine (A):                    3
    Thymine (T):                    3
    Guanine (G):                    4
    Cytosine (C):                   3
    -------------------------------------
    Total Sequence Length:         13 bases
    GC-Content Percentage:      53.85%



### Exercise 4: Tabular String Unpacking & Formatting

Given multi-line raw experimental CSV data:

`data = """S001,E_coli,12.5
S002,E_coli,8.7
S003,S_aureus,15.2
S004,S_aureus,11.4"""`

***Tasks:***
1. Split the multi-line string into rows.
2. Iterate through each row and split by comma delimiter.
3. Extract `sample_id`, `organism`, and cast concentration to `float`.
4. Print each row using arrow-delimited formatting:
    `S001 → E_coli → 12.5 µM`

In [51]:
# Exercise 4: Tabular String Unpacking & Formatting

data = """S001,E_coli,12.5
S002,E_coli,8.7
S003,S_aureus,15.2
S004,S_aureus,11.4"""

# 1. Split multi-line string into rows
rows = data.split("\n")

print("--- Formatted Experimental Log ---")

# 2, 3, 4. Single-pass unpacking, type casting, and arrow formatting
for row in rows:
    # Unpack comma-separated values directly into variables
    sample_id, organism, conc_str = row.split(",")

    # Cast concentration string to float
    concentration = float(conc_str)

    # Print using arrow-delimited formatting with explicit width alignment
    print(f"{sample_id:<6} → {organism:<10} → {concentration:>5.1f} µM")

--- Formatted Experimental Log ---
S001   → E_coli     →  12.5 µM
S002   → E_coli     →   8.7 µM
S003   → S_aureus   →  15.2 µM
S004   → S_aureus   →  11.4 µM


### Exercise 5: Dual-Ordering & Sorting Diagnostics

Given the list of integer measurements:
`values = [17, 3, 25, 8, 12]`

***Tasks:***
1. Produce an ascending order copy using `sorted()`.
2. Produce a descending order list using `.sort(reverse=True)`.
3. Complete the diagnostic reflection block comparing both methods.

#### Sorting Mechanics Reflection

1. **Does `sorted()` modify the original `values` list in memory?** `___`
2. **What value does `values.sort()` return when assigned to a variable (`result = values.sort()`)?** `___`
3. **Why is passing a string number list `["17", "3", "25"]` into `.sort()` catastrophic for numerical data?** `___`

In [3]:
# Exercise 5: Dual-Ordering & Sorting Diagnostics

values = [17, 3, 25, 8, 12]

# 1. Produce an ascending order copy using sorted() (Out-of-place)
ascending_values = sorted(values)
print(f"1. Ascending copy (sorted()):       {ascending_values}")
print(f"   Original list state:             {values}")

# 2. Produce a descending order list using .sort(reverse=True) (In-place)
values.sort(reverse=True)
print(f"2. Descending list (.sort()):        {values}")
print(f"   Original list mutated in-place:  {values}")

1. Ascending copy (sorted()):       [3, 8, 12, 17, 25]
   Original list state:             [17, 3, 25, 8, 12]
2. Descending list (.sort()):        [25, 17, 12, 8, 3]
   Original list mutated in-place:  [25, 17, 12, 8, 3]


#### My Analysis

1. **Does `sorted()` modify the original `values` list in memory?**  
   **No.** `sorted()` is a non-destructive function that allocates a brand-new sorted list object in memory, leaving the original `values` list intact.

2. **What value does `values.sort()` return when assigned to a variable (`result = values.sort()`)?**  
   It returns **`None`**. Assigning `result = values.sort()` sets `result` to `None`. Furthermore, writing `values = values.sort()` will overwrite and destroy your original variable by re-assigning it to `None`.

3. **Why is passing a string number list `["17", "3", "25"]` into `.sort()` catastrophic for numerical data?**  
   Strings sort **lexicographically (alphabetically character-by-character based on ASCII values)** rather than numerically. In string comparison, `'1'` comes before `'2'` and `'3'`, which causes `["17", "3", "25"]` to sort as `['17', '25', '3']` (because `'17'` starts with `'1'`). This leads to corrupted rankings, invalid threshold checks, and flawed numerical analyses.

## 19. Integrated Challenge — Laboratory Sample Manager

This challenge serves as the capstone project for **Notebook 4 (`04_lists.ipynb`)**. 

Build an automated, terminal-driven pipeline that ingests raw multi-line assay exports, parses multi-attribute biological records into parallel data containers, computes statistical metrics manually, and executes interactive custom sorting via `key=` and `lambda`.

---

### Project Scope & Deliverables

Your program must process raw tabular data containing:
- **Sample IDs** (e.g., `"S001"`)
- **Organisms** (e.g., `"E_coli"`)
- **Concentrations ($\mu\text{M}$)** (e.g., `12.5`)

#### System Requirements:
1. **Multi-Stage Text Parsing:** Split raw multi-line CSV text into rows, then split each row into constituent attribute fields.
2. **Type Casting:** Convert string representations of numerical concentrations into `float` values using loops.
3. **Coupling Collections:** Combine parallel lists into paired record tuples (`(sample_id, organism, concentration)`) using `zip()`.
4. **Interactive Sorting Engine:** Prompt the user (`input()`) to select sorting criteria:
   - Option `1`: Sort by **Concentration** (numerical order).
   - Option `2`: Sort by **Sample ID** (lexicographical order).
   - Apply `.sort(key=lambda ...)` to execute the selection in-place.
5. **Statistical Metrics:** Manually compute the **mean concentration** and locate the **sample record with the highest concentration** without using NumPy, Pandas, `sum()`, or `max()`.
6. **Formatted Reporting:** Display a clean tabular summary report.

---

### Technical Constraints

> **Guardrails:**
> - **DO NOT** use external libraries (`numpy`, `pandas`, `math`).
> - **DO NOT** use advanced object structures (`dictionaries`, custom `classes`).
> - **DO** write explicit, manual loop logic for array indexing, type casting, accumulators, and tuple unpacking.

In [8]:
# ==============================================================================
# SECTION 19: INTEGRATED CHALLENGE — LABORATORY SAMPLE MANAGER (SOLUTION)
# ==============================================================================

raw_assay_data = """S001,E_coli,12.5
S002,E_coli,8.7
S003,S_aureus,22.1
S004,S_aureus,15.4
S005,P_aeruginosa,31.0
S006,P_aeruginosa,19.8
S007,E_coli,5.2
S008,S_aureus,11.3"""

# ------------------------------------------------------------------------------
# STEP 1 & 2: Multi-Stage Parsing & Explicit Type Conversion
# ------------------------------------------------------------------------------
rows = raw_assay_data.strip().split("\n")

sample_ids = []
organisms = []
concentrations = []

for row in rows:
    # Unpack comma-separated string fields directly
    sid, org, conc_str = row.split(",")

    # Store attributes in persistent parallel collections
    sample_ids.append(sid)
    organisms.append(org)
    concentrations.append(float(conc_str))  # Type cast to float

# ------------------------------------------------------------------------------
# STEP 3: Coupling Collections into Record Tuples
# ------------------------------------------------------------------------------
# Form paired tuples: (sample_id, organism, concentration)
records = list(zip(sample_ids, organisms, concentrations))
print(records)

# ------------------------------------------------------------------------------
# STEP 4: Interactive Sorting Engine
# ------------------------------------------------------------------------------
print("Select Sorting Option:")
print("1: Concentration (Numerical)")
print("2: Sample ID (Lexicographical)")
choice = input("Enter choice (1 or 2): ")

if choice == "1":
    # Sort in-place by concentration (index 2) descending (highest yield first)
    records.sort(key=lambda record: record[2], reverse=True)
elif choice == "2":
    # Sort in-place by sample ID (index 0) ascending
    records.sort(key=lambda record: record[0])

# ------------------------------------------------------------------------------
# STEP 5: Manual Statistical Accumulation
# ------------------------------------------------------------------------------
total_sum = 0.0
max_record = records[0]  # Full tuple initialized to track ID + Org + Conc

for record in records:
    conc = record[2]

    # Accumulate total sum manually
    total_sum += conc

    # Track maximum sample record manually
    if conc > max_record[2]:
        max_record = record

# Compute mean concentration
mean_conc = total_sum / len(records)

# ------------------------------------------------------------------------------
# STEP 6: Formatted Summary Report
# ------------------------------------------------------------------------------
print("\n" + "=" * 55)
print(f"{'SAMPLE MANAGER REPORT':^55}")
print("=" * 55)
print(f"{'Sample ID':<10} | {'Organism':<15} | {'Concentration':>12}")
print("-" * 55)

for sid, org, conc in records:
    print(f"{sid:<10} | {org:<15} | {conc:>9.2f} µM")

print("=" * 55)
print(f"Total Samples Processed: {len(records):>24d}")
print(f"Mean Concentration:      {mean_conc:>21.2f} µM")
print(
    f"Peak Yield Record:       {max_record[0]} ({max_record[1]}) @ {max_record[2]:.2f} µM"
)
print("=" * 55)

[('S001', 'E_coli', 12.5), ('S002', 'E_coli', 8.7), ('S003', 'S_aureus', 22.1), ('S004', 'S_aureus', 15.4), ('S005', 'P_aeruginosa', 31.0), ('S006', 'P_aeruginosa', 19.8), ('S007', 'E_coli', 5.2), ('S008', 'S_aureus', 11.3)]
Select Sorting Option:
1: Concentration (Numerical)
2: Sample ID (Lexicographical)



                 SAMPLE MANAGER REPORT                 
Sample ID  | Organism        | Concentration
-------------------------------------------------------
S005       | P_aeruginosa    |     31.00 µM
S003       | S_aureus        |     22.10 µM
S006       | P_aeruginosa    |     19.80 µM
S004       | S_aureus        |     15.40 µM
S001       | E_coli          |     12.50 µM
S008       | S_aureus        |     11.30 µM
S002       | E_coli          |      8.70 µM
S007       | E_coli          |      5.20 µM
Total Samples Processed:                        8
Mean Concentration:                      15.75 µM
Peak Yield Record:       S005 (P_aeruginosa) @ 31.00 µM


## 20. Comprehensive Reflection

Reviewing progress across Notebook 4 to consolidate the mental model of lists, tabular data parsing, memory mechanics, and custom sorting logic before transitioning to higher-level data structures.

### 20.1 Core Concepts & Mechanics

#### Lists & Strings
1. **What is a list?**
   * **Answer:** A list is a ordered, mutable sequence container in Python capable of storing dynamic collections of heterogeneous items (integers, floats, strings, or nested lists) under a single variable reference.

2. **How is a list different from a string?** (Consider mutability, element data types, and structural flexibility.)
   * **Answer:** Strings are immutable sequences of single text characters where elements cannot be modified in-place after creation. Lists are mutable containers that allow element insertion, deletion, and direct index modification without re-allocating the entire container.

3. **Why are lists indispensable for biological data processing?**
   * **Answer:** Biological datasets (genomic sequences, assay values, sample metadata) are dynamic, sequential, and multi-attribute. Lists enable manual parsing, memory-efficient updates, element tracking, and customized sorting without requiring external data libraries.

#### Indexing & Slicing
1. **How does zero-based list indexing work? How does negative indexing access elements relative to the end of a list?**
   * **Answer:** Zero-based indexing assigns the first element index `0`, incrementing up to `len(list) - 1`. Negative indexing counts backward from the right end, where `-1` points to the last element, `-2` to the second to last, and so forth.

2. **How does list slicing (`[start:stop:step]`) work? What elements are included or excluded by the `stop` boundary?**
   * **Answer:** Slicing extracts sub-sequences using `[start:stop:step]`. The `start` boundary is inclusive, while the `stop` boundary is exclusive (it cuts off immediately before that index). `step` defines iteration direction and interval.
3. **What happens when you attempt to access an index that does not exist?**
   * **Answer:** Attempting to access an unassigned index (e.g., `sample_list[10]` when `len` is 4) raises an `IndexError: list index out of range`.
#### Mutability & Memory References
1. **What does it mean for a list to be *mutable*?** Contrast this with string immutability.
   * **Answer:** Mutability means a data structure's contents can be altered in-place at its existing memory address. Modifying a string creates a brand-new object in memory, while modifying a list mutates the existing memory block.
2. **What happens when two variables refer to the exact same list in memory (aliasing)?** How does mutating the list through one variable affect the second variable?
   * **Answer:** When two variables point to the same list (aliasing via `b = a`), both variables store identical memory address pointers. Mutating the list through variable `b` immediately reflects in variable `a`.

#### List Operations & Methods
1. **What does `.append()` do, and what does it return?**
   * **Answer:** `.append(item)` appends a single object to the end of a list in-place and returns `None`.
2. **What does `.remove()` do when an element is found? What occurs if the value is not present in the list?**
   * **Answer:** `.remove(val)` searches left-to-right and deletes the first matching instance of `val`, shifting remaining elements left. If `val` is missing, it raises a `ValueError`.
3. **How does `.sort()` differ from `sorted()`?** (Focus on in-place mutation vs. returning a new list copy.)
   * **Answer:** `.sort()` mutates the original list in-place and returns `None`. `sorted(iterable)` leaves the original object untouched and allocates a brand-new sorted list copy.

### 20.2 Data Parsing & Structure

#### Structured Data & Text Extraction
1. **How does `.split()` transform a raw delimiter-separated string into a list of sub-strings?**
   * **Answer:** `.split(delimiter)` scans a string, cuts it at each occurrence of `delimiter`, drops the delimiter characters, and returns a list containing extracted substring fields.
2. **How can multi-line string exports be parsed into individual rows using `.split("\n")` or `.splitlines()`?**
   * **Answer:** Multi-line strings are parsed into discrete record strings by splitting on newline characters (`.split("\n")` or `.splitlines()`).

3. **How do you break down individual row strings into distinct column attributes inside a loop?**
   * **Answer:** Inside a `for` loop iterating over row strings, calling `row.split(",")` breaks each row down into individual column field strings, which can then be unpacked into target variables (`id, org, conc = row.split(",")`).

#### Data Types & Lexicographical Traps
1. **Why is explicit type conversion (e.g., `float()`, `int()`) mandatory after parsing numerical data from text strings?**
   * **Answer:** All values extracted via `.split()` are text strings (`str`). Numerical operations and mathematical sorting fail or sort incorrectly unless strings are explicitly cast using `float()` or `int()`.

2. **How does sorting text strings representing numbers (e.g., `["2", "10", "3"]`) differ from sorting actual numerical types?** What is lexicographical order?
   * **Answer:** Text strings sort lexicographically (character-by-character according to ASCII/Unicode values). Under string sorting, `"10"` precedes `"3"` because `'1'` has a lower ASCII value than `'3'`. Numeric sorting evaluates the full scalar quantity `($3 < 10$)`.

### 20.3 Sequence Pairing & Custom Sorting

#### Zipped Collections (`zip()`)
1. **What specific problem does `zip()` solve when handling parallel lists of data?**
   * **Answer:** `zip()` aggregates elements from two or more parallel sequences position-by-position, forming a sequence of tuple pairs (`(item_A, item_B)`).
2. **What happens to remaining elements when sequences passed to `zip()` have unequal lengths?**
   * **Answer:** `zip()` stops constructing tuples as soon as the shortest input sequence is exhausted, quietly truncating excess elements from longer sequences.

3. **How does changing the tuple positional order in `zip(A, B)` versus `zip(B, A)` alter the default sorting behavior of Python?**
   * **Answer:** Python sorts tuples by index `0` first. `zip(grades, students)` sorts primarily by grade, whereas `zip(students, grades)` sorts primarily by student name.

#### Custom Sorting Keys (`key=` & `lambda`)
1. **What role does the `key=` parameter play in `.sort()` and `sorted()`?**
   * **Answer:** The `key=` parameter accepts a function that extracts a specific comparison value from each element, governing how Python orders items without altering the list's structure.
2. **What is a `lambda` expression, and how does `lambda record: record[1]` select specific tuple elements as the primary sort criteria?**
   * **Answer:** A `lambda` expression is a single-line anonymous function. `lambda record: record[1]` takes a list item (`record`) as input and returns the value at index `1` as the evaluation criteria.

3. **How do you combine `key=lambda ...` with `reverse=True` to rank records in descending numerical order?**
   * **Answer:** Combining `key=lambda record: record[2]` with `reverse=True` evaluates the value at index `2` for every item and orders the records from highest to lowest.

### 20.4 Applied Problem-Solving

1. **Can I construct an automated loop that combines list iteration, manual accumulator counters, and conditional `if`/`elif`/`else` filtering?**
   * **Answer:** Yes. Combining `for` loops, manual accumulators, and conditional logic enables metric calculation and threshold filtering without relying on built-in helper functions or external packages.
2. **Can I ingest a multi-line raw experimental CSV string, cast numerical columns, couple attributes with `zip()`, and render a clean, formatted report?**
   * **Answer:** Yes. A robust parsing pipeline uses `.split("\n")` to separate rows, `.split(",")` to extract attributes, `float()` to convert numerical data, `zip()` to couple fields into record tuples, and `.sort(key=lambda ...)` to generate reports.
3. **Can I explain *why* my program behaves as it does line-by-line, rather than relying on copy-pasted patterns?**
   * **Answer:** Yes. Understanding memory allocation, reference aliasing, loop scopes, and type conversion allows for explicit control over code execution and debugging.

---

### 20.5 Self-Assessment Confidence Check

| Skill / Concept | Confidence (1–5) |
|---|---:|
| Creating homogeneous and heterogeneous lists | 5 |
| Zero-based and negative list indexing | 5 |
| List slicing (`[start:stop:step]`) | 5 |
| Parsing text into lists with `.split()` | 5 |
| Modifying list elements in-place via index assignment | 5 |
| List growth via `.append()` | 5 |
| List item deletion via `.remove()` | 5 |
| Understanding list mutability and memory references | 5 |
| Combining lists with `for` loops and accumulators | 5 |
| Applying conditional threshold logic to list elements | 5 |
| Parsing multi-line raw text into structured rows and columns | 5 |
| Explicit type conversion (`str` $\rightarrow$ `int` / `float`) | 5 |
| Sequence coupling using `zip()` | 5 |
| Handling mismatched sequence lengths in `zip()` | 5 |
| In-place sorting (`.sort()`) vs. returned copy (`sorted()`) | 5 |
| Avoiding the lexicographical sorting trap for numeric strings | 5 |
| Tuple sorting by structural position | 5 |
| Custom key sorting using `key=` parameter | 5 |
| Writing single-line anonymous `lambda` expressions for sorting | 5 |
| Multi-attribute descending sorting using `reverse=True` | 5 |
| Debugging list index and type conversion errors | 5 |
| Building complete, end-to-end data processing pipelines | 5 |